### ISSUE TITLE
 morphology_scripts/evaluation/corpora_validation.py 

### ISSUE THREAD

**Issue by componavt** [lowresource-lang-eval/morphology_scripts#2]
Файл  [morphology_scripts/evaluation/corpora_validation.py](https://github.com/lowresource-lang-eval/morphology_scripts/blob/master/evaluation/corpora_validation.py) 
даёт ошибку:

> TypeError: 'encoding' is an invalid keyword argument for this function

Это лечится заменой строки:
`with open(filename_in, 'r', encoding='utf-8') as f:`

На строку:
`with open(filename_in, 'r') as f:`

Моя версия Питона: 
Python 2.7.15+

**Comment by gisly** [comment]
Да, но предполагали запуск в Python3,
мне кажется, что в Python2 могут потребоваться дополнительные манипуляции с кодировками...

Возможно повысить версию Python до 3 (проверяла на 3.6)?

**Comment by componavt** [comment]
У меня последняя версия Ubuntu 4.18.0, по умолчанию стоит второй Питон.
Пусть тогда мой комментарий будет подсказкой тем, у кого Python2.

P.S. Этот Issue можно закрыть, полагаю.

**Comment by gisly** [comment]
Спасибо за комментарий!

Сама не пользовалась, но, возможно, пригодится https://pypi.org/project/3to2

**Comment by componavt** [comment]
Выяснил две вещи:

1) в Ubuntu есть также программа python3,

2) Python второй некорректно работает с юникодом, в файле со статистикой выдаёт крокозябры.

**Comment by gisly** [comment]
Спасибо, мы тогда будем прописывать в заголовке
#!/usr/bin/python3

**Comment by gisly** [comment]
Со вторым питоном пришлось бы через отдельный модуль codecs работать, видимо.
